
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A455L
 */
public class FrameToko extends javax.swing.JFrame {

    /**
     * Creates new form FrameToko
     */
    public FrameToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namabrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hargabrg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namakasir = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bPrint = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(namabrg);
        namabrg.setBounds(20, 130, 200, 40);

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 80, 50);
        getContentPane().add(hargabrg);
        hargabrg.setBounds(20, 210, 200, 40);

        jLabel4.setText("Harga Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 80, 50);

        namakasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namakasirActionPerformed(evt);
            }
        });
        getContentPane().add(namakasir);
        namakasir.setBounds(20, 290, 200, 40);

        jLabel13.setText("Nama Kasir");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 250, 170, 50);

        jLabel12.setText("Tanggal Transaksi");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 330, 110, 50);

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 0, 36)); // NOI18N
        jLabel1.setText("Toko Nirerror Barakallah");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 0, 330, 60);

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        getContentPane().add(bPrint);
        bPrint.setBounds(400, 380, 110, 30);

        bSave.setText("Save ");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(280, 340, 110, 30);

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete);
        bDelete.setBounds(400, 340, 110, 30);

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        getContentPane().add(bClear);
        bClear.setBounds(280, 380, 110, 30);

        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama ", "Harga", "Kasir", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tb1Data);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 120, 250, 200);
        getContentPane().add(Tanggal);
        Tanggal.setBounds(20, 370, 200, 40);

        jButton1.setText("Refresh Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 70, 120, 30);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 69, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\diseno-decorativo-de-flamenco-en-acuarela_1250-56.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 530, 430);

        setBounds(0, 0, 542, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void namakasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namakasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namakasirActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
         int baris = tb1Data.getSelectedRow();
        if(baris != -1){
            String Nama = tb1Data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM db_barang WHERE nama_brg ='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
           if (status == 1){
        JOptionPane.showMessageDialog(this,"Berhasil","Sukses",JOptionPane.INFORMATION_MESSAGE);
        } else {
        JOptionPane.showMessageDialog(this,"Tidak berhasil","Gagal", JOptionPane.WARNING_MESSAGE);
        }   
      }else{
        JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dulu", "Eror", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String tanggal=dateFormat.format(Tanggal.getDate());
        if ("".equals(namabrg.getText())||"".equals(hargabrg.getText())||"".equals(namakasir.getText())||"".equals(tanggal)) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi data Anda","Error", JOptionPane.WARNING_MESSAGE);
            
        }
        
            String SQL="INSERT INTO db_barang VALUES"
                    +"('"+namabrg.getText()+"','"
                    +hargabrg.getText()+"','"
                    +namakasir.getText()+"','"
                    +tanggal+"')";
            int status=KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal disimpan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        namabrg.setText("");
        hargabrg.setText("");
        namakasir.setText("");
        Tanggal.setCalendar(null);
    }//GEN-LAST:event_bClearActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat ("Stok Barang Toko Nirerror Barakallah");
        MessageFormat footer = new MessageFormat ("Page (0,number,integer");
        
        try{
        tb1Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
        System.err.format("Can't print data", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new TransaksiFrame().show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSave;
    private javax.swing.JTextField hargabrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namabrg;
    private javax.swing.JTextField namakasir;
    private javax.swing.JTable tb1Data;
    // End of variables declaration//GEN-END:variables

   public void selectData(){
        String kolom[] = {"Nama", "Harga", "Kasir", "Tanggal"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM db_barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
            String Nama = rs.getString(1);
            String Harga = rs.getString(2);
            String Kasir = rs.getString(3);
            String Tanggal = rs.getString(4);
            
            String data[] = {Nama,Harga,Kasir,Tanggal};
            dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(FrameToko.class.getName()).log(Level.SEVERE,null,ex);
        } 
        tb1Data.setModel(dtm);
    }
    
    
}
